apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quick-partner-catalog-utx4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quick-partner-catalog-utx4
    app.kubernetes.io/part-of: partner-catalog-2
  name: quick-partner-catalog-utx4
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: quick-partner-catalog-utx4
status:
  loadBalancer: {}
